# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Daniel Spencer
title: Student
email: ddspencer@bsu.edu
phone: 1(219)-730-8639
#website: Your website (eg. https://google.com)(optional)

# Social links
#twitter_username: jekyllrb
github_username:  dxnxxl
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
#linkedin_username: jekyll
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/stairs-2.gif
about_content: | # this will include new lines to allow paragraphs
  Hello, my name is Daniel Spencer. I am from Munster, IN and am currently a senior at Ball State University. 
  
# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  Hobbies
  
  - Music production/Audio Engineering
	- Analog/Digital Photography
	- Cryptocurrency

  
  

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "makefile",
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
